# Question 1

In [2]:
import numpy as np
np.arange(2,50,3)


array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Question 2


In [17]:
import numpy as np
arr=[]
brr=[]
print("Enter the 5 elements in 1st list")
for i in range(5):
    x=float(input("elements:"))
    arr.append(x)
arr=np.array(arr)
print("Array1",np.floor(arr))
print("Enter the 5 elements in 2nd list")
for i in range(5):
    y=float(input("elements:"))
    brr.append(y)
brr=np.array(brr)
print("Array2",np.floor(brr))
crr=np.concatenate((arr,brr))
crr.sort()
print("The final array is:",crr)


Enter the 5 elements in 1st list
elements:1
elements:9
elements:2
elements:5
elements:4
Array1 [1. 9. 2. 5. 4.]
Enter the 5 elements in 2nd list
elements:4
elements:3
elements:2
elements:8
elements:7
Array2 [4. 3. 2. 8. 7.]
The final array is: [1. 2. 2. 3. 4. 4. 5. 7. 8. 9.]


# Question 3


In [19]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("dimension: ",arr.ndim)
print("size: ",arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension:  2
size:  9


# Question 4

In [23]:
import numpy as np
arr=np.array([1,2,3,4])
print("1D Array: ",arr)
new=np.reshape(arr,(-1,2))
print(new)



1D Array:  [1 2 3 4]
[[1 2]
 [3 4]]


In [24]:
import numpy as np
x=np.array([1,2,3,4,5])
y=x[:,np.newaxis]
print(y)

[[1]
 [2]
 [3]
 [4]
 [5]]


# Question 5

In [25]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print("Vertical Stack: \n",np.vstack((arr1,arr2)))
print("Horizontal Stack: \n",np.hstack((arr1,arr2)))

Vertical Stack: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack: 
 [[1 2 5 6]
 [3 4 7 8]]


# Question 6

In order to get a unique items we can use numpy.unique() function and to get count we use np.count_nonzero(np.unique())


In [26]:
arr=np.array([0,1,2,3,4,0,1,6])
np.unique(arr)

array([0, 1, 2, 3, 4, 6])

In [27]:
np.count_nonzero(np.unique(arr))

5